name: Build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wxx9248/zerotier-moon

permissions:
  packages: write

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checking Out Repository
      uses: actions/checkout@v4

    - name: Docker Set up QEMU
      uses: docker/setup-qemu-action@v3.1.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Extract Metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Log in to the Container Registry
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.3.0
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/master' }}
        platforms: >
            linux/amd64,
            linux/386,
            linux/arm64,
            linux/arm/v7,
            linux/ppc64le,
            linux/s390x,
            linux/mips64le
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
